### ISSUE TITLE
Getting "You now need a routing package like useraccounts:iron-routing or..." after user accounts update

### ISSUE THREAD

**Issue by juliomac** [meteor-useraccounts/iron-routing#1]
I have been successfully using user accounts package and it is working fine. However, after I made the upgrade:

```
useraccounts:bootstrap   upgraded from 1.11.1 to 1.12.0
useraccounts:core        upgraded from 1.11.1 to 1.12.0
```

It now asks for this `useraccounts:iron-routing` package.

Do I need it? What are the changes I have to make on my application?

**Comment by splendido** [comment]
Hello @juliomac,

the only this you need is running

`meteor add useraccounts:iron-routing`

and move your old routes configuration after the regular call to `AccountsTemplates.configure` (only in case you had them before it...)
Also make sure your global IR configuration loads before AT routes definition: lets have a look at how I've [changed the bootstrap boilerplate](https://github.com/meteor-useraccounts/boilerplates/commit/a1f8452a84b0ee110bb6663c8209b3f2a9953472).

Hope this helps

**Comment by juliomac** [comment]
Thanks!

I did have to move the old routes after `AccountsTemplates.configure` and all worked fine again.

Best regards! Julio

**Comment by splendido** [comment]
ok, good!
