### ISSUE TITLE
Password token.

### ISSUE THREAD

**Issue by Pierre-Ferreira** [meteor-useraccounts/iron-routing#4]
Hi there.

My enrollment email's button takes me to '/onboarding/step/8/confirm/' with the password token appended.
How do I get the token from the URL? I tried the code below, because the params.token works in Router.route and I thought it would be similar here, but it is not working. Please advise, thanks.

```
AccountsTemplates.configureRoute('enrollAccount', {
    path: '/onboarding/step/8/confirm/:token'
    name: 'enrollaccount',
    layoutTemplate: 'onboardingLayout',data: ->
      { onboardingStep: "8", 
        userToken: params.token
      }
    yieldTemplates: {
      'onboardingNavbar': {to: 'onboarding_navbar'}
      'onboardingMainContent': {to: 'onboarding_main_content'}
      'interActionBoxContentStep8': {to: 'inter-action-box-content'}
    }
});
```

**Comment by splendido** [comment]
You shouldn't be appending the `/:token` at the end of the url, this is already taken care internally. 

If you need to access it, the name used is `paramToken` see [here](https://github.com/meteor-useraccounts/iron-routing/blob/master/lib/core.js#L135)

**Comment by Pierre-Ferreira** [comment]
Got it from this.params.paramToken. Thanks!
