### ISSUE TITLE
Reset password is always redirecting 

### ISSUE THREAD

**Issue by isAlmogK** [meteor-useraccounts/iron-routing#6]
I have a custom template setup 

``` html
<template name="resetPwd">
    <div class="row">
        <div class="col-md-7 col-md-offset-5" style="padding-left: 75px;">
            <br>
            <img src="/images/spoiler-alert-logo-2.png">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-6 col-md-offset-3">
                <br>
                <div class="portlet light">
                    {{> atForm state='resetPwd'}}
                </div>
                <br>
            </div>
        </div>
    </div>
</template>
```

And my route 

``` javascript
Router.route('resetPwd', {
    path: '/reset-password'
});
```

http://localhost:3000/#/reset-password/d2RQzmh_mWzVi6fMvF2iscCoKNRROlXRzxym2ENWMNY

But when I navigate to the reset url it's always redirecting to the main site page and not loading the reset password template

**Comment by splendido** [comment]
hello @almogdesign, you should be configuring the `resetPwd` route like this:

``` javascript
AccountsTemplates.configureRoute('resetPwd', {
    template: 'resetPwd',
});
```

so that the needed configurations and logics are put in place for you by UserAccounts.

Let me know whether this solves your problems or not.
Cheers,
Luca

**Comment by isAlmogK** [comment]
No that did nothing it still redirect back to http://localhost:3000/# 

if I got to http://localhost:3000/reset-password it's fine but the when it has the token it does not work

**Comment by isAlmogK** [comment]
@splendido any news regarding this kind of a major issue?

**Comment by splendido** [comment]
@almogdesign could you have a look at the [boilerplates](https://github.com/meteor-useraccounts/boilerplates)?
They're all up to date with latest versions of Meteor and packages and everything's working fine for them...

**Comment by isAlmogK** [comment]
I have the following packages installed is this incorrect? 

useraccounts:iron-routing
useraccounts:bootstrap

and my router which is pretty straight forward 

https://gist.github.com/almogdesign/6c35399ad9f92a691655

**Comment by isAlmogK** [comment]
The boilerplate examples are not using custom templates I'm creating my own templates and using 

 {{> atForm state='signUp'}}

**Comment by splendido** [comment]
[these lines](https://gist.github.com/almogdesign/6c35399ad9f92a691655#file-router-js-L12-L34) should be changed to ask UserAccounts to set up them properly for you.
See [these lines](https://github.com/meteor-useraccounts/boilerplates/blob/master/bootstrap-iron-router/lib/router/routes.js#L23-L30) in the boilerplate.

Could you please try to insert your custom template into the [bootstrap-iron-routing boilerplate](https://github.com/meteor-useraccounts/boilerplates/tree/master/bootstrap-iron-router) and see whether it works or not?

it should be done somehow like this:

``` javascript
AccountsTemplates.configureRoute('resetPwd', {
  template: 'resetPwd',
});
```

**Comment by almogdesign** [comment]
@splendido  Nope that did not help or do anything attached gif showing the issue 
![redirect-issue](https://cloud.githubusercontent.com/assets/169507/10657774/f18e79fe-7898-11e5-9cb3-107e035f1ce7.gif)

**Comment by isAlmogK** [comment]
@splendido the example you sent is incorrect - 
AccountsTemplates.configureRoute('resetPwd'); 

even this does not work 

AccountsTemplates.configureRoute('resetPwd', {
  template: 'resetPwd',
});

Also the boilerplate is not using custom template but using the templates you provide. I thought the whole point of {{> atForm state='signUp'}} is that I can create what every template I want

**Comment by almogdesign** [comment]
Ok this issue happens even if I don't use a custom template the default useracconts template

**Comment by isAlmogK** [comment]
This only happens when you try to set custom templates - https://github.com/meteor-useraccounts/core/blob/master/Guide.md#templates 

I just tested it with the default templates and it's fine as you can see from the screenshot 
![screen shot 2015-10-22 at 9 23 56 am](https://cloud.githubusercontent.com/assets/169507/10658358/b5d55616-789e-11e5-80b0-21593a40579e.png)

**Comment by isAlmogK** [comment]
Got everything working I had to create the templates with the same name and then use 

AccountsTemplates.configureRoute('verifyEmail', {
    template: 'verifyEmail'
});

**Comment by splendido** [comment]
Glad you got it working!

Btw, your code snippet looks exactly like the one I posted above. The only difference is you're now configuring the `verifyEmail` route while you claimed the problem was with the `resetPwd` one...

Was the issue title wrongly written? 

In any case, just to verify there are no bugs, could you please try to change the name of your custom template to, e.g., `myTemplate` and see whether it still works or not?
...from your last post it might seem that you had to use the `verifyEmail` name for the custom template because different names didn't work.
Is this what you really meant?

**Comment by isAlmogK** [comment]
No the reset password was an issue I had copied the wrong code

**Comment by stinghz** [comment]
@AlmogRnD can you share how did you fix the reset password url issue?
After I upgrade to Meteor 1.3,  I get Urls like 
http://localhost:3000/#/reset-password/xxxxx
http://localhost:3000/#/verify-email/xxxxxx

I'm using flow-router

Any idea of how to fix it is grealy appreciated!

**Comment by stinghz** [comment]
Below is to fix this issue

Accounts.urls.resetPassword = (token) => Meteor.absoluteUrl(`reset-password/${token}`);
Accounts.urls.verifyEmail = (token) => Meteor.absoluteUrl(`verify-email/${token}`);
Accounts.urls.enrollAccount = (token) => Meteor.absoluteUrl(`enroll-account/${token}`);

Accoutns.urls url_server.js srouce code: https://github.com/meteor/meteor/blob/be986fd70926c9dd8eff6d8866205f236c8562c4/packages/accounts-base/url_server.js

**Comment by lo-tp** [comment]
You can customize the resetting page by changing the link sent to the user.

``` js
  Accounts.emailTemplates.resetPassword = {
    from: ()=> "xxxx@test.com",
    subject: ()=> "Reset Your Account Password",
    text: (user, url)=> {
      const newUrl = url.replace("#/reset-password", "setpswd");
      return `Hi,Click the Link below to reset your password:\n${newUrl}`;
    }
  };
```

I have written a gist about the whole customization process.
Check it out [here](https://gist.github.com/lo-tp/f4bc627b4f7c4a37ee4ec68b4e981e2d) for more information.
