### ISSUE TITLE
changePwd route path not working

### ISSUE THREAD

**Issue by louwers** [meteor-useraccounts/iron-routing#7]
``` js
AccountsTemplates.configureRoute('changePwd');
```

works fine.

``` js
AccountsTemplates.configureRoute('changePwd', {
    path: '/wachtwoord-veranderen'
});
```

does not, it says the `/wachtwoord-veranderen` route is not defined.

Something must be wrong, as it is supposed to use the default settings for the other parameters.

**Comment by splendido** [comment]
Hello @louwers!
I've just checked your settings and the route actually exists (writing the whole url into the address bar successfully brings you to the change password page...).

When are you getting the error?
...beware that you might need to specify also the route's name to be able to do something like `Router.go('wachtwoord-veranderen');`.
This would be something like:

``` javascript
AccountsTemplates.configureRoute('changePwd', {
    name: 'wachtwoord-veranderen',
    path: '/wachtwoord-veranderen',
});
```

Let me know if this solves your problem
